apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: k10-backup-pvc
  namespace: kasten-io
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
